export const ADD_FIRST_OPTIONS='ADD_FIRST_OPTIONS';
export const SELECTED_VARIATION='SELECTED_VARIATION';

export const SHOP_NAME_ENTERED='SHOP_NAME_ENTERED';
export const SHOP_SHORT_DESC_ENTERED='SHOP_SHORT_DESC_ENTERED';
export const SHOP_CATEGORY_SELECTED='SHOP_CATEGORY_SELECTED';
export const SHOP_UTN_ADDED='SHOP_UTN_ADDED';
export const SHOP_BA_ADDED='"SHOP_BA_ADDED';
export const SHOP_PROFILE_PICTURE_ADDED='SHOP_PROFILE_PICTURE_ADDED';
export const SHOP_COVER_PHOTO_ADDED='SHOP_COVER_PHOTO_ADDED';


export const OPEN_REGISTER_MODAL='OPEN_REGISTER_MODAL';
export const CLOSE_REGISTER_MODAL='CLOSE_REGISTER_MODAL';
export const ADD_USER_FIRST_NAME='ADD_USER_FIRST_NAME';
export const ADD_USER_LAST_NAME='ADD_USER_LAST_NAME';
export const ADD_USER_EMAIL='ADD_USER_EMAIL';
export const ADD_USER_PASSWORD='ADD_USER_PASSWORD';
export const CONFIRM_PASSWORD='CONFIRM_PASSWORD';

export const PRODUCT_NAME_ENTERED='PRODUCT_NAME_ENTERED';
export const PRODUCT_DESCRIPTION_ENTERED='PRODUCT_DESCRIPTION_ENTERED';
export const PRODUCT_CATEGORY_SELECTED='PRODUCT_CATEGORY_SELECTED';
export const MATERIAL_ADDED='MATERIAL_ADDED';
export const PRODUCT_SKU_ADDED='PRODUCT_SKU_ADDED';
export const PRIMARY_PHOTO_ADDED='PRIMARY_PHOTO_ADDED';
export const LEFT_ANGLE_ADDED='LEFT_ANGLE_ADDED';
export const RIGHT_ANGLE_ADDED='RIGHT_ANGLE_ADDED';
export const DETAILS_PHOTO_ADDED='DETAILS_PHOTO_ADDED';
export const IN_USE_PHOTO_ADDED='IN_USE_PHOTO_ADDED';
export const SCENERY_PHOTO_ADDED='SCENERY_PHOTO_ADDED';
export const FIRST_ATTRIBUTE_SELECTED='FIRST_ATTRIBUTE_SELECTED';
export const SECOND_ATTRIBUTE_SELECTED='SECOND_ATTRIBUTE_SELECTED';
export const THIRD_ATTRIBUTE_SELECTED='THIRD_ATTRIBUTE_SELECTED';
export const PRODUCT_ITEM_ADDED="PRODUCT_ITEM_ADDED";
export const CLEAR_ADD="CLEAR_ADD";
export const DELETE_PRODUCT_ITEM="DELETE_PRODUCT_ITEM";
export const INITIALIZE_ATTRIBUTES='INITIALIZE_ATTRIBUTES';
export const SET_SHOP_ID_FOR_CREATE='SET_SHOP_ID_FOR_CREATE'

export const PRICE_ADDED="PRICE_ADDED";
export const QUANTITY_ADDED="QUANTITY_ADDED";
export const ON_INPUT_ONE="ON_INPUT_ONE";
export const ON_INPUT_TWO="ON_INPUT_TWO";
export const ON_INPUT_THREE="ON_INPUT_THREE";
export const ON_SELECT_ONE="ON_SELECT_ONE";
export const ON_SELECT_TW0="ON_SELECT_TWO";
export const ON_SELECT_THREE="ON_SELECT_THREE";

export const SET_CATEGORY_AS_TREE="SET_CATEGORY_AS_TREE";
export const SET_CATEGORY_AS_LIST="SET_CATEGORY_AS_LIST";


export const SET_UP_PRODUCT="SET_UP_PRODUCT";
export const SET_UP_PRODUCT_PRICE="SET_UP_PRODUCT_PRICE";
export const SET_UP_PRODUCT_PRICE_FOR_SHOW="SET_UP_PRODUCT_PRICE_FOR_SHOW";

export const SET_UP_SHOP="SET_UP_SHOP";
export const SET_NEW_PRODUCTS="SET_NEW_PRODUCTS";

export const SET_ALL_SHOPS="SET_ALL_SHOPS";
export const SET_SHOPS_TOTAL_PAGES="SET_SHOPS_TOTAL_PAGES"
export const SET_SHOPS_FROM_FILTERS="SET_SHOPS_FROM_FILTERS"



