export const ADD_FIRST_OPTIONS='ADD_FIRST_OPTIONS';
export const SELECTED_VARIATION='SELECTED_VARIATION';

export const SHOP_NAME_ENTERED='SHOP_NAME_ENTERED';
export const SHOP_SHORT_DESC_ENTERED='SHOP_SHORT_DESC_ENTERED';
export const SHOP_CATEGORY_SELECTED='SHOP_CATEGORY_SELECTED';
export const SHOP_UTN_ADDED='SHOP_UTN_ADDED';
export const SHOP_BA_ADDED='"SHOP_BA_ADDED';
export const SHOP_PROFILE_PICTURE_ADDED='SHOP_PROFILE_PICTURE_ADDED';
export const SHOP_COVER_PHOTO_ADDED='SHOP_COVER_PHOTO_ADDED';


export const OPEN_REGISTER_MODAL='OPEN_REGISTER_MODAL';
export const CLOSE_REGISTER_MODAL='CLOSE_REGISTER_MODAL';
export const ADD_USER_FIRST_NAME='ADD_USER_FIRST_NAME';
export const ADD_USER_LAST_NAME='ADD_USER_LAST_NAME';
export const ADD_USER_EMAIL='ADD_USER_EMAIL';
export const ADD_USER_PASSWORD='ADD_USER_PASSWORD';
export const CONFIRM_PASSWORD='CONFIRM_PASSWORD';